### ISSUE TITLE
Follow requests

### ISSUE THREAD

**Issue by rugk** [jfilter/frag-den-staat-app#103]
As far as I can see, I cannot follow a request from the app.

Workaround: I can obviously open the web view and follow it there.

**Comment by jfilter** [comment]
Do you have the Beta Version of the App lnstalled?

**Comment by rugk** [comment]
no

**Comment by jfilter** [comment]
Please search in the issues before you create a new one. This feature will come in the version which is currently in beta stage.

https://github.com/jfilter/frag-den-staat-app/issues/68

**Comment by rugk** [comment]
I searched for "follow" or so, but this did not came up. :man_shrugging:  Anyway, good to know thanks…
