### ISSUE TITLE
Cannot get past welcome screen after installing the app

### ISSUE THREAD

**Issue by Yky** [jfilter/frag-den-staat-app#105]
Android P

Installed version 0.10.8 from F-Droid.
Started app
Can neither click next nor skip, making the app unusable.

**Comment by jfilter** [comment]
And swiping is also not working, right?

**Comment by jfilter** [comment]
Could you test it with 0.10.5?

**Comment by jfilter** [comment]
Yes, I can replicate the bug now. It has nothing to do with f droid. I will ship a new version that will hopefully fix it.

**Comment by jfilter** [comment]
Let's hope it's fixed now. If not, feel free to re-open this issue.
