### ISSUE TITLE
F-Droid version is outdated, 0.10.9 is not available

### ISSUE THREAD

**Issue by Yky** [jfilter/frag-den-staat-app#108]
Version 0.10.9 was released 5 days ago on github, but the latest version in F-Droid is still 0.10.8. 

The build is failing: 
https://f-droid.org/wiki/page/de.fragdenstaat.app/lastbuild_41

**Comment by jfilter** [comment]
Thanks for notifying. I hope I can fix it on my own. Otherwise I have to ask for help by the fdroid people. This could take a while. However, the changes to the app from 0.10.8 to 0.10.9  are minimal.

**Comment by Yky** [comment]
https://f-droid.org/wiki/page/de.fragdenstaat.app/lastbuild_42 building 0.10.10 was not successful.

**Comment by mahlzahn** [comment]
Seems, 0.10.10 is on F-Droid since 19/09/2019 and this issue can be closed.

**Comment by jfilter** [comment]
Yeah, cool.
