### ISSUE TITLE
New API Functionality.

### ISSUE THREAD

**Issue by jfilter** [jfilter/frag-den-staat-app#14]
# `GET /api/request/`

- Right now, the names of public body and jurisdiction are not included. But in order to display a list of requests I need the names. Maybe we can include a parameter to specify whether we want the full data for an attribute included in the response or not?
- The same goes for the law within a single FOI request
- On the other hand, the complete message history is always included currently
- Allow the filtering for ‘my requests’ after authorization
- Allow filtering for ‘requests I follow’ after authorization
- Include the ‘notifications’ (comments etc)
- Allow filtering for costs, delayed, category

# `POST /api/request/`
- Allow the creation of new FOI requests

# General
- Follow, unfollow requests
- GZIP, Caching
- Authentication, Authorization

# Later™
-  get 'trending' (based on follower & time) requests
-  [OAuth2](https://github.com/orcasgit/django-tastypie-oauth)

**Comment by arnese** [comment]
Die API ist was für @stefanw

**Comment by jfilter** [comment]
Ich sammle hier erst mal alles was mir so über den Weg läuft und werde ggfs. auch selbst etwas implementieren. MIt der akutellen API komme ich aber schon mal sehr weit.

**Comment by jfilter** [comment]
Moved to https://github.com/okfde/froide/issues/236
