### ISSUE TITLE
PDF-Viewer improvements

### ISSUE THREAD

**Issue by gonium** [jfilter/frag-den-staat-app#43]
The current PDF viewer is not suitable for reading documents on a smart phone. Please implement

* fullscreen mode in order to utilize the full screen real estate
* support landscape mode

In addition, it would be nice (but probably complicated to implement) if the documents could be searched.

**Comment by jfilter** [comment]
The PDF viewer is only to get a glimpse of the document. You can still download the PDF and open it with your local PDF viewer which will most certainly give you a better UX. Search is out of my scope, the same goes for full-screen mode. Landscape mode should be rudimentarily supported but I will work on it in #47.

Nevertheless, I updated the used module and also tweaked it. It should be a little bit better in the next version and I hope it's working for you.

Thanks for your feedback!
