### ISSUE TITLE
Too many app permissions?

### ISSUE THREAD

**Issue by Serkan-devel** [jfilter/frag-den-staat-app#84]
Why are permissions, like device fingerprint and more needed?

**Comment by jfilter** [comment]
Sorry, I can’t follow. Are you talking about the android permissions? I think some permissions are leftovers. What permissions (concrete names) are unnecessary in your opinion?

**Comment by jfilter** [comment]
I certainly didn’t actively put the permission in ;). Let’s see how I get it out. I only need network permission. I am not sure about the SD card part.

**Comment by Serkan-devel** [comment]
You don't even need full network permission to access content from the web

**Comment by jfilter** [comment]
Internet != Web. I use the internet to interact with the FragDenStaat backend. See also: <https://www.google.com/search?q=web internet>

**Comment by jfilter** [comment]
I need access to the internet to send HTTP requests.

**Comment by Serkan-devel** [comment]
@jfilter I've just checked in comparison to browser apps, it's true but what is device finger printing and telephone status for. Reading the SD card is nat necessary, because the app  has storage in it's sandbox. If the user wants to download individual pages permanently, then this permission can be requested later on

**Comment by jfilter** [comment]
I tried to fix this in version 0.9.2. If there are still too many permission, feel free to re-open this issue.

**Comment by Serkan-devel** [comment]
Latest version isn't available on F-Droid though

**Comment by jfilter** [comment]
I will look into this. In general, it can take a while until a version is available on f-droid.
