### ISSUE TITLE
Search for authorities

### ISSUE THREAD

**Issue by Ameinsenbaer** [jfilter/frag-den-staat-app#90]
A feature (like at the website) to make it possible to search for only one authorities.

**Comment by jfilter** [comment]
With authorities you mean public bodies (Behörden)? This should be possible in the search view.

**Comment by jfilter** [comment]
With authority you mean public bodes (Behörden)? This should be possible in the search view.

**Comment by jfilter** [comment]
Closing this for now but feel free to re-open if mean something else.
