### ISSUE TITLE
Error with option: „Gebühr erhoben“

### ISSUE THREAD

**Issue by muescha** [jfilter/frag-den-staat-app#93]
When:
- open app
- select in dropdown the Option „Gebühr erhoben“

What i see:
- error message (in this order after many times of on/off for this option)
  A) undefined
  B) Array.from requires an array-like object - not null or undefined

What i expect:
- no error

**Comment by muescha** [comment]
![e63619b3-bc82-40aa-88df-4b61bb6ececf](https://user-images.githubusercontent.com/184316/52501917-bcff6180-2be1-11e9-81d2-69af7d82c003.png)
![ae0c611e-bae6-4c19-9b42-d30f431a7f99](https://user-images.githubusercontent.com/184316/52501918-bcff6180-2be1-11e9-8fce-efc3537b1c27.png)

**Comment by jfilter** [comment]
Yeah, it's not possible to filter after this property with the API. I disabled it for future releases.
