### ISSUE TITLE
Can't open a request by its direct link

### ISSUE THREAD

**Issue by robbi5** [jfilter/frag-den-staat-app#95]
Since enabling of the universal links (http://fragdenstaat.de/.well-known/apple-app-site-association) the app handles fragdenstaat.de urls on iOS. Tonight I got an email, containing a direct link to the request like https://fragdenstaat.de/a/49930. Tapping it, the app handles this and opens itself - but then shows a pure white screen.

iOS 12.1.4 (16D567)
Model MN922ZD/A
App: Testflight version 0.9.2 (30)

**Comment by jfilter** [comment]
Thanks! Should be fixed in 0.9.3 which I release directly to production since 0.9.2 is already live.
