### ISSUE TITLE
Recent versions cannot be built by F-Droid

### ISSUE THREAD

**Issue by rojoweko** [jfilter/frag-den-staat-app#97]
All versions of frag-den-staat after 0.8.1 fail to be built by F-Droid with the following error message:

FAILURE: Build failed with an exception.

* Where:
Build file '/home/vagrant/build/de.fragdenstaat.app/node_modules/react-native-background-fetch/android/build.gradle' line: 29

* What went wrong:
A problem occurred evaluating project ':react-native-background-fetch'.
> Could not find method compileOnly() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

Any hint to solve the problem would be appreciated! Thanks in advance!

**Comment by jfilter** [comment]
There is already an issue in the f-droid repository: https://gitlab.com/fdroid/fdroiddata/issues/1548

Are you familiar with the whole f-droid build process? I am not an Android expert so I am looking for help to solve this issue.

**Comment by rojoweko** [comment]
Yes, I filed this issue, too, but I was not sure if their or your bug tracker was the right place to address this problem.

Unfortunately I am not really familiar with the f-droid build process, as well. And I am no developer, so I cannot tell, what is causing this. The error message says something about facebook. Is this maybe a non-free dependency that is being referenced here? If yes, can it be stripped from the code by F-Droid without loosing some core functionality? Or does this error occur while building a dependency? I guess this error does not happen when you build this project yourself? Or does it merely not terminate the build process for some reason?

**Comment by jfilter** [comment]
It requires help from somebody familiar with f-droid. I can build and distribute an APK via the Play Store. I'm optimistic that it will get solved soon. Otherwise I will provide an ordinary APK to download.

**Comment by Rudloff** [comment]
Hello,
I [solved](https://gitlab.com/Rudloff/fdroiddata/commit/0c5a6cc1e6a71878d60d9b0d03f51a0068af27da) the build issue in the F-Droid recipe but there is another problem: FragDenStaat now uses the react-native-push-notification library which requires the proprietary Play Services library (and we do not allow proprietary libraries).

**Comment by rojoweko** [comment]
Is it possible to replace or strip this library for the f-droid build without losing major functionality?

**Comment by Rudloff** [comment]
It could technically be patched but this is usually a lot of work and these patches tend to break easily so I'm not sure someone would do it.

**Comment by rojoweko** [comment]
@jfilter: F-Droid requires free (libre) dependencies. Are there any plans to fulfill this requirement in upcoming versions of fragdenstaat?

**Comment by jfilter** [comment]
Yes, I will remove some features for the f droid version and remove this dependency. It’s WIP.

**Comment by jfilter** [comment]
Fixed, the new version will be available soon.

**Comment by rojoweko** [comment]
@jfilter: building on the f-droid build chain seems to work now! Thanks a lot! ;-)

**Comment by jfilter** [comment]
It builds but can you update to the new version in the f droid store?

**Comment by rojoweko** [comment]
The build has already been published and installs successfully on my mobile. ;-)

**Comment by jfilter** [comment]
Awesome, thanks for letting me know!

**Comment by jfilter** [comment]
Could you get passed the welcome screen?

**Comment by rojoweko** [comment]
Yes, I am able to open requests from the main screen.
